### ISSUE TITLE
It works! .. now what do I do?

### ISSUE THREAD

**Issue by flatsiedatsie** [andrenatal/voice-addon#16]
I've installed the addon, and now I hear a ping-ping everytime I say Mozilla. Cool!

So.. now what do I do? 
- What are commands I can use? The Snips.ai website mentions a lot of pre-made commands. Are any of those installed? I tried asking for the time and setting a timer (in English), but neither resulted in any response. 
- Should I / Could I install new commands? 
- Or is my voice transcribed and fed into the Things Gateway Smart Assistant?

**Comment by flatsiedatsie** [comment]
Ah, in the logs I can see things like:

`2019-01-13 21:57:55.976 voice-addon: mensagem no mqtt no addon {"text":"set warmer four ten mint lights","likelihood":0.7033179,"tokens":[{"value":"set","confidence":0.9722156,"range_start":0,"range_end":3,"time":{"start":0.0,"end":1.0845455}},{"value":"warmer","confidence":0.44356894,"range_start":4,"range_end":10,"time":{"start":1.1261169,"end":1.523375}},{"value":"four","confidence":0.7140663,"range_start":11,"range_end":15,"time":{"start":1.5256166,"end":1.6418508}},{"value":"ten","confidence":0.6879254,"range_start":16,"range_end":19,"time":{"start":1.6425952,"end":1.8689593}},{"value":"mint","confidence":0.77010167,"range_start":20,"range_end":24,"time":{"start":1.8689593,"end":2.059897}},
{"value":"lights","confidence":0.7419223,"range_start":25,"range_end":31,"time":{"start":2.059897,"end":2.9329517}}],"seconds":3.0,"siteId":"default","sessionId":"XXXXXXXXXX(redacted by me)"}
`

Which would indicate that it has a hard time understanding what I say :-) (Which in this case was 'Set timer for ten minutes').

What _should_ I tell it?

**Comment by flatsiedatsie** [comment]
Any idea why the voice recognition doesn't recognize the commands? I don't believe I have a strange accent.

**Comment by andrenatal** [comment]
Hi @flatsiedatsie, are you using the latest version of the addon? If yes, you can see the commands being issued in the Event Log page. After having the keyword triggered, you'll need to say something like <action> <thing>, for example 'turn on the kitchen', while <kitchen>  is the name of a thing you have configured in your dashboard.

**Comment by flatsiedatsie** [comment]
I have recently learned that support for things like "set a timer for 5 minutes" and "what time is it", is dependent on the controller (Mozilla Gateway or this add-on) actually being able to handle the command. It doesn't come as 'built in' to snips.

I guess I could turn this question into two feature requests?
- Add support for setting a simple timer
- Add support for telling the time

Should I make this feature request here or with Mozilla? Or is this is a poor request to make?
