### ISSUE TITLE
README references nonexistent "install_script.sh" file

### ISSUE THREAD

**Issue by dholbert** [andrenatal/voice-addon#29]
The README.md installation steps seem to assume that a github clone of this repo will have a `
./install_script.sh` file.  But there is no such file.

Perhaps it really wants to say `package.sh`? That's the only `.sh` file that exists in the clone right now with the executable bit set.

**Comment by dholbert** [comment]
Specifically, here are the steps from README.md that assume such a script exists in this repo:

```
git clone https://github.com/andrenatal/voice-addon
cd voice-addon
[...]
./install_script.sh
```

**Comment by its-leofisher** [comment]
Same issue, I ran the package.sh but thats just to package up the addon I believe.  I then restarted the gateway and it was available in the gateway > addons.

**Comment by andrenatal** [comment]
I'm sorry, but this addon is not supported anymore.
