### ISSUE TITLE
Which USB speaker do you recommend?

### ISSUE THREAD

**Issue by flatsiedatsie** [andrenatal/voice-addon#33]
I don't have a USB speaker, but I might want to try it. Do you have any recommendations? Which one do you use?

**Comment by ricksmit3000** [comment]
i saw it supports respeaker so you'll probably want one of those and connect it with your raspberry pi through micro usb

https://github.com/andrenatal/voice-addon/blob/master/voice-adapter.js#L385

**Comment by flatsiedatsie** [comment]
Thanks. I'm ordering one.
