### ISSUE TITLE
How to handle checksum verification of modified files?

### ISSUE THREAD

**Issue by andrenatal** [andrenatal/voice-addon#7]
@mrstegeman There's a packaged file that is modified by the keyword training, and for that reason, if we disable and re-enable the addon, it won't start because the checksum doesn't match:

`Dec 13 11:30:13 gateway run-app.sh[12285]: 2018-12-13 11:30:13.296 Checksum failed in package voice-addon: personal_kws/config.json`

The only way to fix this is to copy the file during the installation to the target folder or there's some other way?

**Comment by mrstegeman** [comment]
A couple of options:

1. Copy the default file to a new file. It can be in the same directory.
2. Don't add that file to `SHA256SUMS`.

**Comment by andrenatal** [comment]
I thought the checksum for every file was a hard requirement of the API

**Comment by mrstegeman** [comment]
It's certainly ideal, but that's not strictly enforced. Option 1 would be better, though.

**Comment by andrenatal** [comment]
fixed by ecd20bd9ec500711787f2b9621a7a96984c0eb8e
